spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1027936285605-j6ht762ft6t918egov1gd478il0p7j6v.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: gtlqB_7ePWyiOvjI9CaB
            client-secret: 5ttNPtUHKd
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

pay:
  admin-key: 820677c6a3e3cad748d0dc2a66f6296a

